[tool.poetry]
name = "djangobld"
version = "0.1.0"
description = ""
authors = ["IbrahimE11 <ibrahimemad.2002x@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
