# Generated by Django 4.1.2 on 2022-11-02 20:58

import albums.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation_time')),
                ('album_name', models.CharField(default='New Album', max_length=30)),
                ('release_time', models.DateField()),
                ('cost', models.FloatField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('audio', models.FileField(upload_to='audio', validators=[albums.models.validate_file_extension])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
    ]
