# Generated by Django 4.1.2 on 2022-11-10 18:09

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio', validators=[albums.models.validate_file_extension]),
        ),
    ]
