# Generated by Django 4.1.1 on 2022-10-15 13:15

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_time',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation_time'),
        ),
    ]
